# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f9596c8d33f4e853074a40cfba5752227a3ac78420958f065a19056e11f12d8f8ee653800bcf04d7b7de2e85cece26716ba4a727fa84ff25d5b602ec1664cd3

test:
  secret_key_base: 7dd665fdff6510dc9cb0807a1e8a2787f22c29957769be54fc3638c71d01ef96555069cea1c37812d6252abb768d1dabb382a74a34c813f19cbda08c10af0192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
